name: gg_one_merge
description: "Merge flow machinery of the gg_one tool family - merging feature branches via pull requests or local merges."
version: 1.0.0
repository: https://github.com/ggsuite/gg_one_merge.git

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.7.0
  gg_args: ^2.2.0
  gg_console_colors: ^2.3.0
  gg_git: ^3.2.2
  gg_lang: ^0.4.0
  gg_log: ^1.0.6
  gg_merge: ^2.1.1
  gg_one_commit: ^1.0.0
  gg_one_state: ^1.0.0
  gg_process: ^1.1.6
  gg_publish: ^3.10.2
  gg_status_printer: ^1.4.2
  matcher: ^0.12.20
  mocktail: ^1.0.5
  path: ^1.9.1

dev_dependencies:
  gg_capture_print: ^1.0.9
  lints: ^6.1.0
  test: ^1.31.2
